### ISSUE TITLE
Init.d startscript silent failure leading to emails not being delivered

### ISSUE THREAD

**Issue by lgleim** [roehling/postsrsd#59] opened 2016-05-28 19:53 UTC
When trying to debug undelivered outgoing emails (Debian 8) after setting up postsrsd with error messages like the following (/var/log/mail.log)

```
May 28 10:09:34 server postfix/smtpd[12904]: connect from s1.client.ip[X.X.X.X]
May 28 10:09:34 server postfix/smtpd[12904]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
May 28 10:09:35 server postfix/smtpd[12904]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
May 28 10:09:36 server postfix/smtpd[12904]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
May 28 10:09:37 server postfix/smtpd[12904]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
May 28 10:09:38 server postfix/smtpd[12904]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
May 28 10:09:39 server postfix/smtpd[12904]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
May 28 10:09:40 server postfix/smtpd[12904]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
May 28 10:09:41 server postfix/smtpd[12904]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
May 28 10:09:42 server postfix/smtpd[12904]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
May 28 10:09:43 server postfix/smtpd[12904]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
May 28 10:09:43 server postfix/smtpd[12904]: warning: tcp:127.0.0.1:10002 lookup error for "recipient@mydomain"
May 28 10:09:43 server postfix/smtpd[12904]: NOQUEUE: reject: RCPT from s1.client.ip[X.X.X.X]: 451 4.3.0 <recipient@mydomain>: Temporary lookup failure; from=<info@client.ip> to=<recipient@mydomain> proto=ESMTP helo=<client.ip>
```

I discovered that the init.d scipt silently failed to start the postsrsd daemon. 
Turns out that postsrsd fails with error 

> postsrsd: extra argument on command line:

if the SRS_EXCLUDE_DOMAINS variable is empty, i.e. if calling postsrsd with argument 

`-X ""`

I fixed it temporarily by simply removing the -X flag, however I suggest you might want to take another look at either the init.d script (additional if-clause) or the implementation of the -X flag.

**Comment by roehling** [comment] 2016-05-28 21:48
This looks like a duplicate of #44, and should be fixed in the latest version. AFAIK Debian still uses the older 1.2 release.

**Comment by lgleim** [comment] 2016-05-29 06:54
It is the same issue. Sorry for missing that. However I built from master yesterday so I am wondering why the generated upstart script still has the space in between -X and it's parameter. Any ideas?

**Comment by roehling** [comment] 2019-01-11 15:22
I have just released a new version that should resolve the -X parameter problem for good. I hope.

**Closed by roehling** 2019-01-11 15:22 UTC
