### ISSUE TITLE
SRS_EXCLUDE_DOMAINS not working

### ISSUE THREAD

**Issue by jranma** [roehling/postsrsd#86] opened 2019-01-03 08:55 UTC
Hi, This setting does nothing on my debian stretch server. Adresses from the exclude domains are rewritten...

Here is the setting I'm using: 
SRS_EXCLUDE_DOMAINS=domain1,domain2,domain3

ps -ax:
0:00 /usr/local/sbin/postsrsd -f 10001 -r 10002 -d mydomain.com -s /etc/postsrsd.secret -a = -n 4 -N 4 -u nobody -p /var/run/postsrsd.pid -c /usr/local/lib/postsrsd -D -Xdomain1 domain2 domain3

(is it intended that the parameter "X" is not followed by a space before the first domain?)

I'm using init.d to restart the process: /etc/init.d/postsrsd

I tried replacing comas by spaces with no luck. 
I'm willing to help debuging !

**Comment by ziirish** [comment] 2019-01-11 14:54
I'm having the same issue on debian stretch

**Comment by roehling** [comment] 2019-01-11 15:07
Duplicate of #74

**Closed by roehling** 2019-01-11 15:07 UTC
